version: "3.3"

services:
        gunicorn-container:
                build: ./gunicorn
        nginx:
                build: ./nginx
                ports:
                        - "5000:5000"
                depends_on:
                        - gunicorn-container
